[tool.poetry]
name = "lunchmenu"
version = "0.1.0"
description = ""
authors = ["Daniel Trnka <daniel.trnka@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.8"
httpx = "^0.27.0"
selectolax = "^0.3.21"
fastapi = "^0.111.0"
uvicorn = {extras = ["standard"], version = "^0.30.1"}
redis = {extras = ["hiredis"], version = "^5.0.7"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
